
image:
#  - Visual Studio 2015
  - Ubuntu

# TODO: Fix cygwin-unix build:    - OS: unix
#environment:
#  matrix:
#    - OS: win32

install:
  - sh: sudo dpkg --add-architecture i386 && sudo apt-get -yq update && sudo apt-get -yq install build-essential gcc-multilib php
  - sh: sudo apt-get -yq install tcl-dev:i386 libcurl4-openssl-dev:i386
  - sh: apt-get download tk8.6-dev:i386 tk-dev:i386 && sudo dpkg -i --force-all *.deb
  - cmd: SET PATH=C:\Ruby25\bin;%PATH%
  - cmd: gem install bundler jekyll
  - cmd: "C:/cygwin/setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup 
-P 
git,make,gcc-core,mingw64-i686-gcc-core,libcrypt-devel,mingw64-i686-libgcrypt,mingw64-i686-curl,tcl-tk-devel,mingw64-i686-tcl,mingw64-i686-tk,zip,php,procps"

build_script:
  - sh: cd $APPVEYOR_BUILD_FOLDER/unix && make
  - cmd: C:\Cygwin\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/win32 && make"

test_script:
  - sh: cd $APPVEYOR_BUILD_FOLDER/unix && make test
  - cmd: C:\Cygwin\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/win32 && make test"
